name: Generate Gradle Wrapper

on:
  workflow_dispatch:

jobs:
  generate-wrapper:
    name: Generate Gradle Wrapper Files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Create minimal Gradle build
      run: |
        echo "rootProject.name = 'gradle-wrapper-gen'" > settings.gradle
        echo "// empty build file" > build.gradle

    - name: Install Gradle temporarily
      uses: gradle/actions/setup-gradle@v3

    - name: Generate Gradle Wrapper (v7.4)
      run: gradle wrapper --gradle-version 7.4

    - name: Upload Wrapper Files as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: gradle-wrapper
        path: |
          gradlew
          gradlew.bat
          gradle/wrapper/
